swagger: '2.0'
info:
  title: Azure Health Data Services de-identification service Collection WorkspacePrivateLinkResources API
  version: '2024-11-15'
  x-typespec-generated:
  - emitter: '@azure-tools/typespec-autorest'
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- AadToken:
  - https://deid.azure.com/.default
tags:
- name: WorkspacePrivateLinkResources
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HealthcareApis/workspaces/{workspaceName}/privateLinkResources
  : get:
      tags:
      - WorkspacePrivateLinkResources
      operationId: WorkspacePrivateLinkResources_ListByWorkspace
      description: Gets the private link resources that need to be created for a workspace.
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/workspaceName'
      responses:
        '200':
          description: The request was successful; the request was well-formed and received properly.
          schema:
            $ref: '#/definitions/PrivateLinkResourceListResultDescription'
        default:
          description: DefaultErrorResponse
          schema:
            $ref: '#/definitions/ErrorDetails'
      x-ms-examples:
        WorkspacePrivateLinkResources_ListGroupIds:
          $ref: ./examples/privatelink/PrivateLinkResourcesListByWorkspace.json
      x-ms-pageable:
        nextLinkName: null
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HealthcareApis/workspaces/{workspaceName}/privateLinkResources/{groupName}
  : get:
      tags:
      - WorkspacePrivateLinkResources
      operationId: WorkspacePrivateLinkResources_Get
      description: Gets a private link resource that need to be created for a workspace.
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/workspaceName'
      - name: groupName
        in: path
        description: The name of the private link resource group.
        required: true
        type: string
      responses:
        '200':
          description: The request was successful; the request was well-formed and received properly.
          schema:
            $ref: '#/definitions/PrivateLinkResourceDescription'
        default:
          description: DefaultErrorResponse
          schema:
            $ref: '#/definitions/ErrorDetails'
      x-ms-examples:
        WorkspacePrivateLinkResources_Get:
          $ref: ./examples/privatelink/WorkspacePrivateLinkResourceGet.json
definitions:
  ErrorDetails:
    description: Error details.
    type: object
    properties:
      error:
        description: Error details
        $ref: '#/definitions/ErrorDetailsInternal'
  PrivateLinkResourceListResultDescription:
    type: object
    properties:
      value:
        type: array
        description: Array of private link resources
        items:
          $ref: '#/definitions/PrivateLinkResourceDescription'
    description: A list of private link resources
  ErrorDetailsInternal:
    description: Error details.
    type: object
    properties:
      code:
        description: The error code.
        type: string
        readOnly: true
      message:
        description: The error message.
        type: string
        readOnly: true
      target:
        description: The target of the particular error.
        type: string
        readOnly: true
  PrivateLinkResourceDescription:
    type: object
    properties:
      systemData:
        description: Metadata pertaining to creation and last modification of the resource.
        $ref: ../../../../../../common-types/resource-management/v1/types.json#/definitions/systemData
    allOf:
    - $ref: ../../../../../../common-types/resource-management/v1/privatelinks.json#/definitions/PrivateLinkResource
    description: The Private Endpoint Connection resource.
parameters:
  workspaceName:
    name: workspaceName
    in: path
    required: true
    type: string
    description: The name of workspace resource.
    x-ms-parameter-location: method
    minLength: 3
    maxLength: 24
  resourceGroupName:
    name: resourceGroupName
    in: path
    description: The name of the resource group that contains the service instance.
    required: true
    type: string
    x-ms-parameter-location: method
    pattern: ^[-\w\._\(\)]+$
    minLength: 1
    maxLength: 90
securityDefinitions:
  AadToken:
    type: oauth2
    description: The Azure Active Directory OAuth2 Flow
    flow: accessCode
    authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    scopes:
      https://deid.azure.com/.default: ''
    tokenUrl: https://login.microsoftonline.com/common/oauth2/token
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - name: endpoint
    in: path
    description: Url of your De-identification Service.
    required: true
    type: string
    format: uri
    x-ms-skip-url-encoding: true
